# Generated by Django 4.1.3 on 2022-12-20 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_BLOG', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
