# Generated by Django 4.1.3 on 2022-12-24 20:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WEB_BLOG', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avatar',
            new_name='ImagenPerfil',
        ),
    ]
