# Generated by Django 4.1.3 on 2022-12-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_BLOG', '0005_posteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
