# Generated by Django 4.1.3 on 2022-12-27 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_BLOG', '0007_alter_posteo_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteo',
            old_name='user',
            new_name='usuario',
        ),
    ]
