# Generated by Django 4.1.3 on 2022-12-27 02:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_BLOG', '0008_rename_user_posteo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
