# Generated by Django 4.1.3 on 2023-01-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_BLOG', '0010_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
