# Generated by Django 4.1.3 on 2023-01-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_BLOG', '0011_chatmessage_remove_message_sender_delete_chat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
